2021-Aug-15 배열과리스트의차이
PoorStackDeveloper/Tech-Interview pull request #1
Opened 2021-08-15 13:38 UTC by jyeonjyan

제가 한번 정리를 해보았습니다 !

2021-08-15 14:41 UTC, siwony requested changes
수고하셨습니다 👍 
comment확인해주세요

2021-08-15 14:41 UTC, siwony commented on question/배열과리스트의차이.md
> +# 배열(Array)과 리스트(List)의 차이
해당 글에서의 리스트는 연결리스트로 설명하고 있지만
리스트는 배열과 연결리스트를 포함하는 종합적인 단어 입니다. 순서를 가지고 일렬로 나열만 하면 리스트가 될 수 있어요!
배열과 연결리스트의 차이로 정정해주세요 :)

참고자료 입니다: 
https://opentutorials.org/module/1335/8636

https://namu.wiki/w/%EB%A6%AC%EC%8A%A4%ED%8A%B8(%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0)

https://junstar92.tistory.com/51

2021-08-16 03:22 UTC, jyeonjyan commented on question/배열과리스트의차이.md
> +# 배열(Array)과 리스트(List)의 차이
### 참고자료를 읽어 보았으나, 배열과 리스트로 표기해도 문제 없을 것 같다는 의견입니다.

<img width="170" alt="Screen Shot 2021-08-16 at 12 09 22 PM" src="https://user-images.githubusercontent.com/67095821/129506428-34947c79-209e-4f41-9af4-4e36652d8529.png">

구글링 해서 Array 와 List 자체를 구분 짓는 레퍼런스를 참고해보세요 (글쓴이 모든 사람들이 틀렸을까요?)

참고자료 첫 번째는 `ArrayList` 와 `LinkedList` (java)스크립트 언어를 기준으로 한 비교이기 때문에 
**죄송하지만, 모든 영역에서의 Array 랑 List 의 비교의 적절한 예시가 될 수 없습니다 ^^**

참고자료 두 번째 나무위키 말을 인용하자면 
> 때문에 배열을 리스트의 일종으로 볼 수도 있다.

"일종으로 볼 수 있다." 가 "아닌 일종으로 볼 수도 있다." 라고 말 하네요.

결론적으로 @siwony 님의 말이 틀렸다는게 아닙니다.
> 하지만, 리스트는 배열과 연결리스트를 포함하는 종합적인 단어 입니다.

라는 말은 아닌 것 같다는 생각이 듭니다.

[참고자료](https://gbsb.tistory.com/310)
> 본래 리스트(List)는 추상 자료형이므로 구현 방법이 정의되어 있지 않다. 리스트를 구현하려면, 배열(Array) 또는 연결 리스트(LinkedList)를 이용하면 된다. 보통 리스트를 구현할 때 연결 리스트를 많이 사용하기 때문에, 리스트와 연결 리스트를 동의어로 많이 사용하고 있다.

2021-08-16 03:48 UTC, jyeonjyan commented on question/배열과리스트의차이.md
> +# 배열(Array)과 리스트(List)의 차이
[참고자료](https://www.studytonight.com/data-structures/linked-list-vs-array)
여러가지 참고해보니 @siwony 님의 의견대로 LinkedList 라고 명확히 표시하는게 더 CS 다운 Heading 이 될 수 있겠네요.
감사합니다 이런 좋은 의견 🙇🏻‍♂️

2021-08-16 04:18 UTC, merged

2021-08-16 04:52 UTC, siwony commented on question/배열과리스트의차이.md
> +# 배열(Array)과 리스트(List)의 차이
> [참고자료](https://www.studytonight.com/data-structures/linked-list-vs-array)
> 여러가지 참고해보니 @siwony 님의 의견대로 LinkedList 라고 명확히 표시하는게 더 CS 다운 Heading 이 될 수 있겠네요.
> 감사합니다 이런 좋은 의견 🙇🏻‍♂️

요즈음에 리스트를 연결리스트의 동의어로 사용한다는 사실은 처음알았네요!

하지만 명확한 의미를 전달해야 하는 글에는 `LinkedList`라고 명시하는게 좋을 거 같아요
리스트와 배열을 비교하여 설명했던 블로그 중에 저런 사항을 명시하지 않아 틀렸다고 생각했습니다. :)